# Generated by Django 5.1.2 on 2024-10-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_shop_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="shop",
            name="slug",
        ),
    ]
